### ISSUE TITLE
[Nit] Consider using upright parentheses in italic text

### ISSUE THREAD

**Issue by MarcinCiura** [jemmybutton/byrne-euclid#10]
Hi, Sergey.  Byrne uses upright parentheses in propositions.  Bringhurst's *Elements of Typographic Style* also [recommend them](https://tex.stackexchange.com/questions/13048/upright-parentheses-in-italic-text).  Caveat: I am not sure what to do when the closing parenthesis is followed by another punctuation mark like the colon in proposition IV of book I.

**Comment by jemmybutton** [comment]
Hi, Mciura. I agree with you, upright parentheses look better. The solutions you provide link to seem to be LaTeX specific, it will take some time to figure out how to do it properly in ConTeXt.

**Comment by jemmybutton** [comment]
Hi, Marcin. Better late than never: this https://github.com/jemmybutton/byrne-euclid/commit/6bb880ed70b43c1148eac75bb9c805ee4f1539b4#diff-acb525a5a0669b6175601decd8757cf1R18 seems to turn parentheses in italics upright. Basically, it's a fallback, which forces parenthesis from "roman" into "italic", but it seems not to break anything and look ok.

**Comment by mciura** [comment]
A possible alternative is to use math parentheses. Their disadvantage is no line breaks between `\left(` and `\right)` unless you break the equation and use `\vphantom` or substitute `\Big` etc. for `\left` and `\right`.
![parens](https://user-images.githubusercontent.com/1486557/60161220-5c229f80-97f7-11e9-862c-a35fec0d2cd4.png)

**Comment by jemmybutton** [comment]
@mciura Also math parentheses won't be very convenient when it comes to text. I'll try to find a way to change metrics for these two characters (parentheses) in italics in order for them to look as of they respect italics correction. Or maybe adopt some other solution.

**Comment by jemmybutton** [comment]
@mciura [This](https://tex.stackexchange.com/questions/497851/upright-parentheses-in-italic-text-in-context#497861) seems to be a working solution.

**Comment by jemmybutton** [comment]
@mciura Adding this line https://github.com/jemmybutton/byrne-euclid/commit/aecd132808870799d7615ebedb2841b71ef5add2#diff-ce29b5befc0686b45157d97a74d17263R20 fixes this problem. Although i don't understand yet why it works.
