### ISSUE TITLE
[Nit] Horizontal lines are above the math axis

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#11]
In Byrne's edition, inlined horizontal lines lie at the same height as the horizontal line in + and −.

**Comment by jemmybutton** [comment]
Thank you for pointing this out, it really does look a little sloppy. It will take some time to figure out the right way to do it.

**Comment by mciura** [comment]
I tried to get from LuaTex the value of the math axis of the math font and failed.  Instead, simple changing https://github.com/jemmybutton/byrne-euclid/blob/master/preamble.tex#L110 to
```
\middp=0.4\ht0
\midht=0.6\ht0
```
gave me lines perfectly (within the resolution of my PDF viewer) aligned with the horizontal axis from page 12 of `byrne_ru_context.pdf` on.  However, on page 7, the horizontal lines lie too high — I don't know why.

**Comment by jemmybutton** [comment]
@mciura i'm sorry for not responding for so long. as far as i understand, what you want, is to play with \ht and \dp ( as shown on the picture here https://tex.stackexchange.com/a/41014/99551 ) of every box containing an image of some line. the lines you have modified do just that, but relative to the height of the box. I'd rather change the lines below ( https://github.com/jemmybutton/byrne-euclid/blob/923151740e0101eec396c188cd917b82da938095/preamble.tex#L112 ) that address the same thing, but in absolute values, like this:
```
\advance\middp by -2.75pt
\advance\midht by 2.75pt
```
(this value works well enough for me:
![well_enough](https://user-images.githubusercontent.com/7447349/37796148-9dd50714-2e27-11e8-8334-2f1ca3abe076.png)
)

**Comment by jemmybutton** [comment]
NB. I'm not closing the issue, since this is not _the_ solution to this problem, i guess.

**Comment by mciura** [comment]
Thank you for the solution, Sergey.  Here is my fragment of `preamble.tex`:
```
                \middp=0.5\ht0
                \midht=0.5\ht0
                \advance\middp by -2.75pt
                \advance\midht by 2.75pt
```
It seems to fix the position of **unlabeled** lines only, like on page 7.  Labeled lines, like on page 29 (see the picture below), are still at wrong height.
![lines](https://user-images.githubusercontent.com/1486557/37952717-0c00dafc-31a1-11e8-8b79-2ddf742ac8f4.png)

**Comment by jemmybutton** [comment]
@mciura Sorry again for not responding for so long.
This is a dirty fix, but seems to work: https://github.com/jemmybutton/byrne-euclid/commit/13076ca04f98a16a47abe27eb717d1621ee857c5#diff-729a8dc19cc1aa522f18a5cd5cda0084R805
![aligned](https://user-images.githubusercontent.com/7447349/38177613-b9c164e4-360c-11e8-85a6-aa1f57d140e5.png)
The images of the labels are just placed on the bottom of the line in white, so the overall picture is always symmetrical no matter with or without labels.

**Comment by mciura** [comment]
Thank you for the solution.  It looks like `\drawPoint` needs some adjustment, too. Otherwise the lines it draws lie on another height than the lines drawn by `\drawUnitLine`.
![drawpoint](https://user-images.githubusercontent.com/1486557/38458736-de6262be-3aa1-11e8-9cf3-c0376077d0c5.png)

**Comment by jemmybutton** [comment]
The same trick won't work as good in this case, since points can be drawn on arbitrary set of line segments, not just horizontal lines:
![pointa](https://user-images.githubusercontent.com/7447349/38460616-099c16cc-3ac6-11e8-81ee-a59cccf080a0.png)
Maybe i'll try to add some kind of phantom label anyway. 
And in general it seems that there needs to be a macro to shift pictures up and down when it's not automated for some reason.
