### ISSUE TITLE
Some typos in byrne_context.pdf

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#12]
Page 31: add a period before "For", replace the final semicolon with a period.
Page 34: remove \therefore before "hence" (this is Byrne's typo).
Page 38: replace a comma with a period before "Then".
Page 39: replace "for" with "For", add a period at the end.
Page 40: add a period at the end.
Page 43: add a period at the end (this is Byrne's typo).
Page 44: add a period at the end of the proposition.
Page 45: add a period before "But" (this is Byrne's typo).
Page 46: replace a comma with a period before "Then".
Page 48: add a period at the end.
Page 50: add a comma and a period to the second and third lines in the brace at the end.
Page 55: add a period before "Consequently".
Page 59: replace a semicolon with a period before "Then" or replace "Then" with "then" (this is Byrne's typo).
Page 61: add a period at the end (this is Byrne's typo).
Page 63: replace a colon with a period before "Therefore" or replace "Therefore" with "therefore" (this is Byrne's typo).
Page 64: add a period before "But" (this is Byrne's typo).
I have got to go now.  Hope this helps.

**Comment by mciura** [comment]
Page 15, definition 6: s/extramities/extremities/

**Comment by jemmybutton** [comment]
Thank you, this is very helpful! I've [fixed these and a lot of similar ones](https://github.com/jemmybutton/byrne-euclid/commit/f6eb2088ca7b6caaedd49d80a4656cf9482c958b). 
[byrne_context.pdf](https://github.com/jemmybutton/byrne-euclid/files/1347158/byrne_context.pdf)
