### ISSUE TITLE
Bug in Book III Prop. XVIII

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#14]
In the proof, the yellow and red angles are swapped both in the English and the Russian version.

**Comment by jemmybutton** [comment]
As far as i understand the proof, if FG is perpendicular to CG, angle FGC (the yellow one) must be equal to the right angle (but on the picture it, of course, looks acute) and (in the triangle FGC) the angle GCF (the red one) must be acute (but is in fact right). And this is proven to be absurd. Everything looks correct. Or i'm missing something?
![iii-xviii](https://user-images.githubusercontent.com/7447349/31306241-68f4f9e2-ab54-11e7-8dc9-d21bb84557ee.png)

**Comment by mciura** [comment]
You are right.  I missed the "if it be possible part".  Sorry for the noise.

**Comment by jemmybutton** [comment]
It's ok, thank you anyway. This proposition is an example when Byrne's approach can actually make things a little bit more confusing than they would be without any pictures at all. And i'm not sure if it's possible to redraw this diagram to make these equations with angles much more convincing.
