### ISSUE TITLE
Mistranscribed text in line 1113 of byrne_context.tex

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#16]
s/A square is described on a line/The square described on a line/
https://archive.org/stream/firstsixbooksofe00eucl#page/n31/mode/2up

**Comment by jemmybutton** [comment]
Thinks! [Fixed](https://github.com/jemmybutton/byrne-euclid/commit/e211ea02ad618f9149ffb43027d43ee5ead43fff#diff-ce29b5befc0686b45157d97a74d17263R1113)
