### ISSUE TITLE
[Typo] ,% in line 118 of byrne_context.tex

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#19]
No space before the percent sign produces "form,but" (without a space) in the output.

**Comment by jemmybutton** [comment]
Sorry for adding this space so long, i forgot to commit this fix https://github.com/jemmybutton/byrne-euclid/commit/a6a10d7367125d932ac7f424d35aa675c487a50a#diff-ce29b5befc0686b45157d97a74d17263R118
