### ISSUE TITLE
Typos in byrne_ru_context.tex

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#21]
1308: missing period
1351: совпает

**Comment by mciura** [comment]
1623: probably missing пополам

**Comment by jemmybutton** [comment]
Thank you!
Fixed: https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1308
Fixed: https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1351
And fixed: https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1623
