### ISSUE TITLE
Bug in proposition I.VII

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#22]
As I understand it, line 1499 of the English version and line 1507 of the Russian version compare wrong pairs of segments. The body of `\eqalign` should say
`\drawUnitLine{CA}&=\drawUnitLine{DA}\cr \drawUnitLine{BC}&=\drawUnitLine{BD}`
instead of 
`\drawUnitLine{CA}&=\drawUnitLine{BC}\cr \drawUnitLine{DA}&=\drawUnitLine{BD}`.

**Comment by jemmybutton** [comment]
Thank you, that's absolutely correct, fixed:
https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-ce29b5befc0686b45157d97a74d17263R1499
https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1507
