### ISSUE TITLE
Bug in proposition I.IX

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#23]
Lines 1572 (English) and 1566 (Russian) say `D := A yscaled -1;`.  As triangle BCD is equilateral, they should say `D := (0, -2.3094u);` instead.  To differentiate it visually from a mirror image of triangle ABC, I suggest also, say, `A := (0, 5/3u);` three lines above.

**Comment by jemmybutton** [comment]
Thanks a lot! In the original it does look like a mirror image and i didn't look further into this proof. Now triangle BCD will always be equilateral:
https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-ce29b5befc0686b45157d97a74d17263R1569
https://github.com/jemmybutton/byrne-euclid/commit/d4a933a8ba3da001229a7e1ac757f5e23ede5b4f#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1563
