### ISSUE TITLE
Missing label C in the diagram in Proposition I.XIV

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#25]

**Comment by jemmybutton** [comment]
Fixed!
https://github.com/jemmybutton/byrne-euclid/commit/65f086cf1085994504bfb164c9c93af024d4bbfd#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1799
and
https://github.com/jemmybutton/byrne-euclid/commit/65f086cf1085994504bfb164c9c93af024d4bbfd#diff-ce29b5befc0686b45157d97a74d17263R1802
