### ISSUE TITLE
In proposition I.XV, axiom III should be referenced instead of axiom II

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#30]

**Comment by mciura** [comment]
And in proposition I.XVI, `$\therefore \anglesECDpDCF\ > \drawAngle{ECD}$.`  should be `$\therefore \anglesECDpDCF\ > \drawAngle{B}$.`

**Comment by mciura** [comment]
And in proposition I.XVIII, `$\drawAngle{ABC} > \drawAngle{D}$ \inprop[prop:I.XVI]` should say `$\drawAngle{A} > \drawAngle{D}$ \inprop[prop:I.XVI]`.

**Comment by mciura** [comment]
In the diagram in proposition I.XXIII, the labels D and E are probably unnecessary.
Also, "между любыми двумя точками сторонами данного угла" in the same proposition doesn't make sense to me.

**Comment by mciura** [comment]
In proposition I.XXVIII, axiom III is misplaced. In fact, axiom I should be referenced there; axiom III should be referenced one line below.

**Comment by mciura** [comment]
In proposition I.XXXV, "Но" makes little sense. As I understand it, it should say e.g. "Поэтому" instead and refer to `\inprop[I.XXVI]` rather than `\inprop[I.VIII]`. The problem with this correction is, this is not how Euclid's proof looks like (https://archive.org/stream/euclid_heath_2nd_ed#page/n339/mode/2up).

**Comment by jemmybutton** [comment]
> In proposition I.XV, axiom III should be referenced instead of axiom II
Fixed: https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1847

> And in proposition I.XVI, $\therefore \anglesECDpDCF\ > \drawAngle{ECD}$. should be $\therefore \anglesECDpDCF\ > \drawAngle{B}$.
Fixed: https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-ce29b5befc0686b45157d97a74d17263R1891
https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1889

> And in proposition I.XVIII, $\drawAngle{ABC} > \drawAngle{D}$ \inprop[prop:I.XVI] should say $\drawAngle{A} > \drawAngle{D}$ \inprop[prop:I.XVI].
Fixed: https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-ce29b5befc0686b45157d97a74d17263R1982
https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R1980
Note that I've also changed variable names here.

Thank you very much! I did think that there are many errors left, but not _so_ many.

> In the diagram in proposition I.XXIII, the labels D and E are probably unnecessary.
Also, "между любыми двумя точками сторонами данного угла" in the same proposition doesn't make sense to me.
Fixed: https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R2227

> In proposition I.XXVIII, axiom III is misplaced. In fact, axiom I should be referenced there; axiom III should be referenced one line below.
Fixed only in Russian (missing in the original): https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R2539

> In proposition I.XXXV, "Но" makes little sense. As I understand it, it should say e.g. "Поэтому" instead and refer to \inprop[I.XXVI] rather than \inprop[I.VIII]. The problem with this correction is, this is not how Euclid's proof looks like (https://archive.org/stream/euclid_heath_2nd_ed#page/n339/mode/2up).
Fixed only in Russian: https://github.com/jemmybutton/byrne-euclid/commit/86318bc29685e5fd523e898e734a2e4039add586#diff-5a8eec69ed8a2717ec1a6d8ee3f6ac94R2836
I agree, proof as it is in the original, seems to make little sense, and switching 'but' and 'therefore' seems much better to me. It well may be a typo in the original, and in that case I should change it also in the English version.
