### ISSUE TITLE
Bug in proposition I.XXXV

### ISSUE THREAD

**Issue by gpierron** [jemmybutton/byrne-euclid#33]
EDIT: sorry, bug was present in pdf release, not in actual source code. Apologies.

------
Hi and thanks for your work.

there's a bug in I.35 second-to-last line. Should be : 
**trapezium** minus triangle 

thank you

**Comment by jemmybutton** [comment]
Thank you anyway, sorry for the inconvenience. I hope to prepare new release with all the fixes, some time soon.
