### ISSUE TITLE
--WithName functions removal

### ISSUE THREAD

**Issue by jemmybutton** [jemmybutton/byrne-euclid#42]
With this https://github.com/jemmybutton/byrne-euclid/commit/e629c3ea82f8a3c2959a96d49133e35211210f1e i want to eventually get rid of all the --WithName functions, replacing them with extended syntax for their ordinary counterparts: for instance you can type `byAngleDefine.someAngle(A, B, C, byred, 0);`instead of `byAngleDefineWithName(A, B, C, byred, 0)(someAngle);`
For now --WithName ones are still there, so everything should work as before. @mciura would you mind switching to the new syntax at some point?

**Comment by jemmybutton** [comment]
At the next stage objects that need name by default (like circles and arcs) will get auto naming and will use similar syntax.

**Comment by mciura** [comment]
@jemmybutton Thank you for the heads-up. Sure thing, I will switch.

**Comment by jemmybutton** [comment]
Docs are updated https://github.com/jemmybutton/byrne-euclid/commit/ec06b44292429d35249ab2307bb41a399d19138a
