### ISSUE TITLE
\inprop[prop:I.I] does not produce a reference

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#51]
![propi-i](https://user-images.githubusercontent.com/1486557/59846988-a0c6ba80-9361-11e9-98ce-78facda3c3da.png)
As far as I can tell, all the other references work as intended.

**Comment by jemmybutton** [comment]
@mciura Sorry, i made a mistake, fixed https://github.com/jemmybutton/byrne-euclid/commit/ac2ff26e609c5871307e3e534e044075d8875038#diff-b44801cabf4c040d727c2524313832c6R351
