### ISSUE TITLE
File lettrines/lettrineslist.txt is empty

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#52]
```
$ context byrne_context.tex
$ ls -l lettrines/lettrineslist.txt 
-rw-r--r-- 1 marcin marcin 0 cze 20 18:32 lettrines/lettrineslist.txt
```

**Comment by jemmybutton** [comment]
@mciura Instead of closing the file with sizes i accidentally closed the file with lettrines list. Fixed https://github.com/jemmybutton/byrne-euclid/commit/ac2ff26e609c5871307e3e534e044075d8875038#diff-b44801cabf4c040d727c2524313832c6R144
