### ISSUE TITLE
Lettrines not appearing for all lines on bk 1 prop XXiX

### ISSUE THREAD

**Issue by bgeorge77** [jemmybutton/byrne-euclid#56]
Oddly, the lettrines for lines AB, CD, and GH do not appear in the main drawing for this prop.

EDIT: I am using the English version with the lettrines turned on and the custom line numbers and large angles.

**Comment by jemmybutton** [comment]
Sorry, my mistake, thank you for letting me know. Fixed. Here you go:
[byrne_context_withlabels_large_diagrams.pdf](https://github.com/jemmybutton/byrne-euclid/files/4051726/byrne_context_withlabels_large_diagrams.pdf)
