### ISSUE TITLE
Typo: Book 1, p32. page 57: line 1: "by" should be "be"

### ISSUE THREAD

**Issue by bgeorge77** [jemmybutton/byrne-euclid#57]
Typo: Book 1, prop 32. page 57: line 1: "by" should be "be"

**Comment by jemmybutton** [comment]
@bgeorge77 Thank you! Fixed:
[byrne_context_withlabels_large_diagrams.pdf](https://github.com/jemmybutton/byrne-euclid/files/4067700/byrne_context_withlabels_large_diagrams.pdf)
