### ISSUE TITLE
Book 1 Prop XLII p 67: Misalignment of the image

### ISSUE THREAD

**Issue by bgeorge77** [jemmybutton/byrne-euclid#58]
The image overlaps the text. 

I am using the custom version with line numbers. 

[https://github.com/jemmybutton/byrne-euclid/files/4067700/byrne_context_withlabels_large_diagrams.pdf](url)

**Comment by jemmybutton** [comment]
Fixed!
[byrne_context_withlabels_large_diagrams.pdf](https://github.com/jemmybutton/byrne-euclid/files/4176980/byrne_context_withlabels_large_diagrams.pdf)
