### ISSUE TITLE
Mistranscribed text in byrne_context.tex, line 1087

### ISSUE THREAD

**Issue by jovipueyo** [jemmybutton/byrne-euclid#63]
The quotation "two straight lines which contain one **if** its right angles." should be "two straight lines which contain one **of** its right angles."
Thank you so much for this work.

**Comment by jemmybutton** [comment]
Thank you! Fixed now https://github.com/jemmybutton/byrne-euclid/commit/e481fc2e479451198141d782b5d7af33f78bcd9d
Keep in mind that this version can, unfortunately, have issues in the layout due to a bug in the ConTeXt version I'm using https://github.com/jemmybutton/byrne-euclid/issues/62 .
