### ISSUE TITLE
\drawCurrentPictureInMargin leaves a spurious space

### ISSUE THREAD

**Issue by mciura** [jemmybutton/byrne-euclid#8]
Hi Sergey.  Please take a look at page 15 of byrne_context.pdf — the text of definition 8 starts correctly, while the text of definition 9 has a spurious space at its beginning.  Same goes for all pieces of text accompanied by a picture in the margin.
All the best,
  Marcin Ciura

**Comment by jemmybutton** [comment]
Hi Mciura. Thanks! That extra space seem to appear only if, ultimately, `\inouter` ConTeXt macro is placed before `\startalignment`. I've [moved it inside](https://github.com/jemmybutton/byrne-euclid/commit/af0a366e718b18e5b278538146654806a2e37135) and everything seems to work ok now.
Check out [byrne_context.pdf](https://github.com/jemmybutton/byrne-euclid/files/1346686/byrne_context.pdf)
